import type { ThemeConfig } from "antd";
import { palette } from "./palette";

// Fields show focus with a darker grey border only, no glow ring (3.2:1 contrast on white).
const fieldHoverBorder = "#B8BEC8";
const fieldFocusBorder = palette.placeholder;

const overlayShadow = "0 0 0 1px rgba(11,18,32,0.06), 0 1.5rem 3rem -0.75rem rgba(11,18,32,0.28)";
const popoverShadow =
  "0 0 0 1px rgba(11,18,32,0.06), 0 0.25rem 0.75rem -0.125rem rgba(11,18,32,0.08), 0 0.75rem 1.5rem -0.25rem rgba(11,18,32,0.10)";

export const antdTheme: ThemeConfig = {
  token: {
    colorPrimary: palette.brand,
    colorInfo: palette.brand,
    colorLink: palette.brand,
    colorLinkHover: palette.brandHover,
    colorSuccess: palette.success,
    colorWarning: palette.warning,
    colorError: palette.danger,

    colorTextBase: palette.ink,
    colorText: palette.ink,
    colorTextSecondary: palette.muted,
    colorTextTertiary: palette.muted,
    colorTextQuaternary: palette.subtle,
    colorTextPlaceholder: palette.placeholder,
    colorTextDisabled: palette.subtle,

    colorBorder: palette.lineStrong,
    colorBorderSecondary: palette.line,
    colorSplit: palette.line,
    colorBgLayout: palette.app,
    colorBgContainer: palette.surface,
    colorBgElevated: palette.surface,
    colorBgMask: "rgba(11, 18, 32, 0.25)",
    colorFill: palette.line,
    colorFillSecondary: palette.selected,
    colorFillTertiary: palette.hover,
    colorFillQuaternary: palette.hoverSubtle,
    colorBgTextHover: palette.hover,
    colorBgTextActive: palette.selected,
    controlItemBgHover: palette.hover,
    controlItemBgActive: palette.hover,
    controlItemBgActiveHover: palette.selected,

    // Fonts come from the CSS variables in index.css, so switching fonts is a one-place change.
    fontFamily: "var(--font-sans)",
    fontFamilyCode: "var(--font-mono)",
    fontSize: 13,
    fontSizeSM: 11,
    fontSizeLG: 13,
    fontSizeXL: 15,
    lineHeight: 1.5385,
    fontWeightStrong: 600,

    borderRadius: 6,
    borderRadiusXS: 2,
    borderRadiusSM: 4,
    borderRadiusLG: 8,
    borderRadiusOuter: 4,
    controlHeight: 34,
    controlHeightXS: 20,
    controlHeightSM: 28,
    controlHeightLG: 38,
    controlOutline: "rgba(45, 91, 255, 0.18)",
    controlOutlineWidth: 3,
    lineWidthFocus: 2,

    boxShadow: overlayShadow,
    boxShadowSecondary: popoverShadow,
    boxShadowTertiary: "0 0.0625rem 0.125rem rgba(11,18,32,0.06), 0 0 0 1px rgba(11,18,32,0.04)",

    motionDurationFast: "0.1s",
    motionDurationMid: "0.15s",
    motionDurationSlow: "0.2s",
  },
  components: {
    Button: {
      fontWeight: 500,
      contentFontSize: 13,
      contentFontSizeLG: 13,
      contentFontSizeSM: 13,
      paddingInline: 12,
      paddingInlineLG: 16,
      paddingInlineSM: 8,
      onlyIconSize: 16,
      onlyIconSizeSM: 14,
      primaryShadow: "none",
      defaultShadow: "none",
      dangerShadow: "none",
      defaultBorderColor: palette.lineStrong,
      defaultColor: palette.ink,
      defaultHoverBg: palette.hoverSubtle,
      defaultHoverBorderColor: palette.lineStrong,
      defaultHoverColor: palette.ink,
      defaultActiveBg: palette.hover,
      defaultActiveBorderColor: palette.lineStrong,
      defaultActiveColor: palette.ink,
      textHoverBg: palette.hover,
      textTextHoverColor: palette.ink,
    },
    Input: {
      activeShadow: "none",
      errorActiveShadow: "none",
      warningActiveShadow: "none",
      hoverBorderColor: fieldHoverBorder,
      activeBorderColor: fieldFocusBorder,
      paddingInline: 10,
      paddingInlineLG: 12,
      inputFontSize: 13,
      inputFontSizeLG: 13,
    },
    Select: {
      activeOutlineColor: "transparent",
      activeBorderColor: fieldFocusBorder,
      hoverBorderColor: fieldHoverBorder,
      optionHeight: 32,
      optionFontSize: 13,
      optionPadding: "0.375rem 0.5rem",
      optionSelectedBg: palette.hover,
      optionSelectedColor: palette.ink,
      optionSelectedFontWeight: 500,
      optionActiveBg: palette.hoverSubtle,
    },
    Checkbox: {
      colorPrimary: palette.ink,
      colorPrimaryHover: palette.inkHover,
      colorBorder: palette.lineStrong,
      borderRadiusSM: 4,
      controlInteractiveSize: 16,
    },
    Switch: {
      colorPrimary: palette.ink,
      colorPrimaryHover: palette.inkHover,
    },
    Menu: {
      itemHeight: 32,
      itemBorderRadius: 6,
      itemMarginInline: 0,
      itemMarginBlock: 1,
      itemPaddingInline: 8,
      itemColor: palette.muted,
      itemHoverColor: palette.ink,
      itemHoverBg: palette.hover,
      itemSelectedBg: palette.selected,
      itemSelectedColor: palette.ink,
      itemActiveBg: palette.selected,
      iconSize: 16,
      iconMarginInlineEnd: 10,
      activeBarBorderWidth: 0,
      fontSize: 13,
    },
    Tree: {
      titleHeight: 30,
      nodeHoverBg: palette.hover,
      nodeSelectedBg: palette.selected,
      nodeSelectedColor: palette.ink,
      fontSize: 13,
    },
    Dropdown: {
      paddingBlock: 6,
      controlPaddingHorizontal: 8,
      borderRadiusLG: 8,
      borderRadiusSM: 6,
      fontSize: 13,
    },
    Tooltip: {
      colorBgSpotlight: palette.ink,
      borderRadius: 6,
      fontSize: 11,
      paddingSM: 8,
      paddingXS: 4,
    },
    Breadcrumb: {
      itemColor: palette.muted,
      linkColor: palette.muted,
      linkHoverColor: palette.ink,
      lastItemColor: palette.ink,
      separatorColor: palette.subtle,
      separatorMargin: 6,
      fontSize: 13,
    },
    Table: {
      headerBg: palette.surface,
      headerColor: palette.muted,
      headerSplitColor: "transparent",
      headerBorderRadius: 0,
      borderColor: palette.lineSoft,
      rowHoverBg: palette.hoverSubtle,
      rowSelectedBg: palette.rowSelected,
      rowSelectedHoverBg: palette.rowSelectedHover,
      cellFontSize: 13,
      cellFontSizeMD: 13,
      cellFontSizeSM: 13,
      cellPaddingBlockMD: 10,
      cellPaddingInlineMD: 12,
      headerSortActiveBg: palette.surface,
      headerSortHoverBg: palette.hoverSubtle,
      bodySortBg: "transparent",
      selectionColumnWidth: 40,
      footerBg: palette.surface,
    },
    Pagination: {
      itemSize: 28,
      itemSizeSM: 28,
      itemBg: "transparent",
      itemActiveBg: palette.surface,
      itemActiveColor: palette.ink,
      itemActiveColorHover: palette.ink,
      itemLinkBg: "transparent",
      colorPrimary: palette.ink,
      colorPrimaryHover: palette.ink,
      colorPrimaryBorder: palette.lineStrong,
      fontSize: 13,
      fontSizeSM: 13,
      borderRadius: 6,
    },
    Segmented: {
      trackBg: palette.hover,
      trackPadding: 3,
      controlHeight: 34,
      controlHeightSM: 28,
      borderRadius: 8,
      borderRadiusSM: 6,
      itemColor: palette.muted,
      itemHoverColor: palette.ink,
      itemHoverBg: "transparent",
      itemActiveBg: "transparent",
      itemSelectedBg: palette.surface,
      itemSelectedColor: palette.ink,
      boxShadowTertiary: "0 0.0625rem 0.125rem rgba(11,18,32,0.08), 0 0 0 1px rgba(11,18,32,0.05)",
      fontSize: 13,
    },
    Notification: {
      width: 360,
    },
    Modal: {
      borderRadiusLG: 12,
      titleFontSize: 15,
      titleLineHeight: 1.4,
      headerBg: palette.surface,
      contentBg: palette.surface,
    },
    Alert: {
      withDescriptionPadding: "0.625rem 0.75rem",
    },
  },
};
