// Mirrors the @theme tokens in index.css so antd and Tailwind share one palette.
export const palette = {
  brand: "#2D5BFF",
  brandHover: "#1F45D6",
  brandSoft: "#EAF0FF",
  ink: "#0B1220",
  muted: "#5B6474",
  subtle: "#A3AAB6",
  line: "#E3E6EB",
  lineStrong: "#D5DAE1",
  surface: "#FFFFFF",
  app: "#F6F7F9",
  hover: "#F0F2F5",
  hoverSubtle: "#F9FAFB",
  selected: "#E9ECF0",
  lineSoft: "#EEF0F3",
  placeholder: "#8B93A1",
  rowSelected: "#F5F8FF",
  rowSelectedHover: "#EEF3FF",
  inkHover: "#1F2937",
  success: "#16A34A",
  warning: "#F5A524",
  danger: "#E5484D",
};
